use_frameworks!

target 'KRMLogger_Example', :exclusive => true do
  pod 'KRMLogger', :path => '../'
end

target 'KRMLogger_Tests', :exclusive => true do
  pod 'KRMLogger', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
